### ISSUE TITLE
Conversion process for Training Notes to documentation

### ISSUE THREAD

**Issue by KipTwitchell** [genevaers/doc#18]
The video training produced 10 years ago has some very well-edited contents in the speaker notes.  Here are the steps one can use to extract these notes efficiently, and use the graphics in the PPT to make documentation pages.

1) Open the PPT in Google Docs (slides)
2) Select Google Docs File (not your browser File menu)
3) Select Download/Plain Text File

You now have a text file that contains the text from the slide AND the notes.

4) Open this file
5) Paste into a MD file in a MD Editor
6) Do some Global Search and Replaces:
  a) Replace of "SAFR" with "GenevaERS"
  b) Replace "IBM Scalable Architecture for Financial Reporting" with noting
  c) Replace "© Copyright IBM Corp. 2012" with "with "© Copyright IBM Corp. 2012, licensed under Apache 2.0 to the GenevaERS project"  The year might be different.
    d) Replace "Course materials may not be reproduced in whole or in part without the prior written permission of IBM." with nothing
7) Typically Slides 1, 2 and 3 have no meaningful graphic in the slide, so just extract the notes text to begin the document
8) Convert the "module" terminology to documentation.  For example, make the "This module provides you with a broad overview of the SAFR product and the basics of its graphical user interface. By the end of this training, you should be able to:" language into "This page provides you with a broad overview of GenevaERS and the basics of its graphical user interface. It will help you:"  
9) Drop the final few pages, including the trademark discloser pages.
10) Use the remaining text to build the documentation page

For those slides where the slide graphic is useful 
11) edit the PPT
  a) Repeat the search and replace features above
  b) Export the slides to jpegs
  c) Rename the exported files from "Slide1" etc. to something meaningful for the page
  d) Keep all the images for the web page together in a single folder
  e) delete the IBM logo from the slide master template
12) Copy the image folder to the Images Directory in the markdown repo
13) Insert links into the documentation using Markdown syntax

**Comment by KipTwitchell** [comment]
Additionally, use the following syntax for inserting the graphics.

<div style="clear: right" > <img style="float: right;" width="50%" vspace="5" alt="GenevaERS Edit New Source 2" src=images/Module1-Introduction-to-Views/Module1_Slide22.jpeg title="GenevaERS Edit New Source 2"/>

Here's an explanation of the parameters.

<div style="clear: right" >          This keeps the graphics from floating on top of each other.  It clears the float of the prior graphic.  This like can also be used before a ## heading in MD so the heading shows below the prior graphic
<img style="float: right;"        This aligns the graphic to the right
width="50%"                           this reduces the size of the graphic
vspace="5"                              this puts space between graphics when they are stacked 
alt="GenevaERS Edit New Source 2"     Text if the graphic doesn't show up.
src=images/Module1-Introduction-to-Views/Module1_Slide22.jpeg  file name (in directory) of the graphic.
title="GenevaERS Edit New Source 2"/>  Text that shows on mouse roll-over

**Comment by KipTwitchell** [comment]
@emorrow38 I have converted all the training materials into the Markdown Test Repo.  It's a good starting point for documentation if you are ready to migrate to the doc repo.  

Thanks for your encouragement.  I'm glad to have gotten that done, and please with the results.

**Comment by emorrow38** [comment]
Thank you Kip, every topic helps - we'll find a place for them all.
